linters:
  disable-all: true
  enable-all: false
  fast: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - containedctx
    # - contextcheck # TODO evaluate
    # - cyclop
    # - decorder
    # - depguard
    # - dogsled
    - dupl
    - durationcheck
    - errcheck
    # - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustruct
    - exportloopref
    - forbidigo
    # - forcetypeassert
    # - funlen
    # - gci
    # - ginkgolinter
    # - gochecknoglobals
    - gochecknoinits
    # - gocognit
    # - goconst
    - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    # - gofmt
    - gofumpt
    # - goheader
    - goimports
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    # - grouper
    # - importas
    - ineffassign
    # - interfacebloat
    # - ireturn
    # - lll
    # - logrlint
    # - maintidx
    - makezero
    # - misspell
    - nakedret
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    # - paralleltest
    # - prealloc
    - predeclared
    - promlinter
    - revive
    # - rowserrcheck # disabled because of generics
    - sqlclosecheck
    - staticcheck
    # - stylecheck
    # - tagliatelle
    - tenv
    # - testpackage
    # - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varnamelen
    # - wastedassign # disabled because of generics
    - whitespace
    # - wrapcheck
    # - wsl
